name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: creyD/prettier_action@v4.2
        with:
          prettier_version: 2.8.8
          prettier_options: --write .
          prettier_plugins: '@prettier/plugin-php@0.19.7'
          commit_message: 'Run Prettier'
